<?php

namespace App\Services\Bot;

/**
 * The HMAC signature for `POST /internal/actions` on the bot (TOG-44, TOG-470).
 *
 * Ported from the working reference signer rather than from prose: two-bot
 * `scripts/internal-actions-acceptance.ts` at `origin/tog-463/acceptance-harness`
 * (`b42037c`), canonical string at line 56. `docs/INTERNAL_ACTIONS.md` v0.3 §1
 * describes the same thing in English, but English is not what the bot verifies
 * against, so tests/Unit/Bot/InternalActionSignerTest.php pins this class to
 * vectors generated by that TypeScript, not to the paragraph.
 *
 * Nothing here touches the network or the config. It is pure string work on
 * purpose: the one part of this feature that is impossible to eyeball for
 * correctness is the part that must be testable without a bot to talk to.
 */
final class InternalActionSigner
{
    /**
     * Signed literally, and therefore a constant rather than something parsed
     * back out of the configured URL. The bot builds its own canonical string
     * from its own route; if we ever signed a path derived from
     * `BOT_ENDPOINT_URL` then a trailing slash in an .env would present as an
     * unexplained 401 rather than as the config typo it is.
     */
    public const PATH = '/internal/actions';

    /**
     * How the body is encoded before it is signed *and* sent.
     *
     * The flags are not cosmetic. The reference signer hashes the bytes of
     * JavaScript's `JSON.stringify`, which escapes neither `/` nor non-ASCII.
     * PHP's default does both, so an announcement containing a URL or an
     * accented character would hash differently here than everywhere else this
     * wire format is exercised. We sign what we send, so either would actually
     * verify — but a body that is byte-identical to the reference keeps the
     * cross-checked vectors in the test suite meaningful.
     */
    public const JSON_FLAGS = JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR;

    /**
     * 128 bits, hex — the width §1 documents. Fresh on every attempt including
     * retries, which is why this is a function and not a value held anywhere.
     */
    public static function nonce(): string
    {
        return bin2hex(random_bytes(16));
    }

    public static function bodyHash(string $rawBody): string
    {
        return hash('sha256', $rawBody);
    }

    /**
     * `"POST\n/internal/actions\n{timestamp}\n{nonce}\n{sha256_hex(raw_body)}"`.
     *
     * @param  string  $rawBody  the exact bytes that will go on the wire
     */
    public static function canonical(string $timestamp, string $nonce, string $rawBody): string
    {
        return implode("\n", [
            'POST',
            self::PATH,
            $timestamp,
            $nonce,
            self::bodyHash($rawBody),
        ]);
    }

    /**
     * `"sha256=" + hex(hmac_sha256(secret, canonical))`, lowercase hex.
     *
     * Note the argument order of PHP's `hash_hmac`: data first, key second. It
     * is the opposite of how the formula reads and swapping them produces a
     * perfectly plausible-looking hex string that the bot rejects as
     * `unauthorized`. The pinned vectors catch it.
     */
    public static function sign(string $secret, string $timestamp, string $nonce, string $rawBody): string
    {
        return 'sha256='.hash_hmac('sha256', self::canonical($timestamp, $nonce, $rawBody), $secret);
    }

    /**
     * Encode a payload to the bytes that will be both signed and sent.
     *
     * Callers must keep the return value and send *it* — re-encoding the array
     * a second time to build the request body is the mistake §1 calls out, and
     * it presents as an intermittent 401 rather than as anything obvious.
     *
     * @param  array<string, mixed>  $payload
     */
    public static function encode(array $payload): string
    {
        return json_encode($payload, self::JSON_FLAGS);
    }
}
