#!/usr/bin/env bash
#
# Make headless Chrome runnable in an agent sandbox, without root.
#
# For a long time this company believed no agent could run a browser, so nothing
# visual was ever verified by looking at it — a11y, layout and performance claims
# all rested on reading code. That belief was wrong, and it cost us a false "live
# on staging" report to the owner on TOG-48.
#
# The image ships Chrome (via the puppeteer cache) but none of its shared
# libraries: `ldd` reports 25 "not found". We are uid 1000 with no sudo, so they
# cannot be installed the normal way. But `apt-get` will happily *download* as a
# normal user once every path it wants to write to is redirected somewhere
# writable, and `dpkg-deb -x` unpacks a .deb into a plain directory. Point
# LD_LIBRARY_PATH at that directory and Chrome starts. No root, no image change.
#
# On GitHub Actions this is unnecessary — `ubuntu-latest` already has the
# libraries — and the script detects that and exits early rather than spending
# two minutes proving it.
#
# Idempotent: re-running only re-unpacks. ~2 min cold, ~280MB on disk.
#
# Usage: ./ci/browser/install-chrome-deps.sh   then   source ci/browser/env.sh
set -euo pipefail

PREFIX="${CHROME_DEPS_PREFIX:-/paperclip/.cache/chrome-deps}"
WORK="$PREFIX/.work"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Chrome's actual dynamic-link closure on Debian 13. apt computes the transitive
# dependencies from these, so this list stays short.
#
# The t64 suffixes are load-bearing. Debian's 64-bit-time_t transition left BOTH
# names in the archive: `libcups2` still resolves, but it is an empty transitional
# shim whose only content is a dependency on `libcups2t64`. Seed the bare name and
# apt reports success while unpacking no .so at all — the failure surfaces much
# later as Chrome refusing to start, with nothing pointing back to here. Six
# libraries hit this. Verify with the ldd count at the end, never apt's exit code.
SEEDS=(
  libnss3 libnspr4 libatk1.0-0t64 libatk-bridge2.0-0t64 libcups2t64 libdrm2
  libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2
  libgbm1 libpango-1.0-0 libcairo2 libasound2t64 libatspi2.0-0t64
  libglib2.0-0t64 libdbus-1-3 libx11-6 libxcb1 libxext6 libexpat1
  fonts-liberation libfontconfig1 libfreetype6
)

find_chrome() {
  # Prefer an explicit CHROME_BIN, then the puppeteer cache, then a system Chrome
  # (which is what CI runners have).
  if [ -n "${CHROME_BIN:-}" ] && [ -x "${CHROME_BIN}" ]; then
    echo "$CHROME_BIN"; return
  fi
  local c
  c="$(ls -d "${PUPPETEER_CACHE_DIR:-/paperclip/.cache/puppeteer}"/chrome/linux-*/chrome-linux64/chrome 2>/dev/null | sort -V | tail -1 || true)"
  [ -n "$c" ] && { echo "$c"; return; }
  command -v google-chrome-stable || command -v google-chrome || command -v chromium || true
}

write_env() {
  # $1 = prefix to put on LD_LIBRARY_PATH, or empty for "no prefix needed"
  local prefix="$1" chrome="$2"
  if [ -n "$prefix" ]; then
    cat > "$HERE/env.sh" <<EOF
# Generated by install-chrome-deps.sh — source this before driving Chrome.
export CHROME_DEPS_PREFIX="$prefix"
export LD_LIBRARY_PATH="\$CHROME_DEPS_PREFIX/usr/lib/x86_64-linux-gnu:\$CHROME_DEPS_PREFIX/lib/x86_64-linux-gnu\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export FONTCONFIG_PATH="\$CHROME_DEPS_PREFIX/etc/fonts"
export CHROME_BIN="$chrome"
EOF
  else
    cat > "$HERE/env.sh" <<EOF
# Generated by install-chrome-deps.sh — source this before driving Chrome.
# This host already satisfies Chrome's shared libraries; no prefix needed.
export CHROME_BIN="$chrome"
EOF
  fi
}

CHROME="$(find_chrome)"
[ -n "$CHROME" ] || { echo "no Chrome binary found (set CHROME_BIN)" >&2; exit 1; }

# Already satisfied? Then there is nothing to install. This is the CI path.
if [ "$(ldd "$CHROME" 2>/dev/null | grep -c 'not found' || true)" -eq 0 ]; then
  echo "==> Chrome's libraries are already satisfied on this host; nothing to do."
  write_env "" "$CHROME"
  "$CHROME" --version
  exit 0
fi

mkdir -p "$PREFIX" "$WORK"/{lists/partial,aptcache/archives/partial,debs}
: > "$WORK/status"   # empty dpkg status => apt assumes nothing is installed

# Every Dir::* override matters: without them apt tries /var/lib/apt and aborts
# on EACCES. The "partial" subdirs must exist or apt refuses to start.
APT_OPTS=(
  -o "Dir::State::Lists=$WORK/lists"
  -o "Dir::State::status=$WORK/status"
  -o "Dir::Cache=$WORK/aptcache"
  -o "Dir::Cache::archives=$WORK/aptcache/archives"
  -o "Debug::NoLocking=1"
  -o "APT::Sandbox::User=root"
)

echo "==> apt-get update (unprivileged)"
apt-get "${APT_OPTS[@]}" update >/dev/null 2>&1 || true

echo "==> resolving + downloading dependency closure"
cd "$WORK/debs"
apt-get "${APT_OPTS[@]}" download $(apt-cache "${APT_OPTS[@]}" depends --recurse --no-recommends --no-suggests \
  --no-conflicts --no-breaks --no-replaces --no-enhances "${SEEDS[@]}" 2>/dev/null \
  | grep "^\w" | sort -u) >/dev/null 2>&1 || true

COUNT=$(ls -1 "$WORK/debs"/*.deb 2>/dev/null | wc -l)
echo "    $COUNT packages downloaded"
[ "$COUNT" -gt 0 ] || { echo "no packages downloaded; apt sources may be unreachable" >&2; exit 1; }

echo "==> unpacking into $PREFIX"
for deb in "$WORK"/debs/*.deb; do
  dpkg-deb -x "$deb" "$PREFIX" 2>/dev/null || echo "    skipped $(basename "$deb")" >&2
done

write_env "$PREFIX" "$CHROME"
# shellcheck disable=SC1090
source "$HERE/env.sh"

# The only assertion that means anything. apt exits 0 having unpacked nothing.
MISSING=$(ldd "$CHROME_BIN" 2>/dev/null | grep -c "not found" || true)
echo "==> missing shared libraries: $MISSING"
[ "$MISSING" -eq 0 ] || {
  echo "still unsatisfied — add the names ldd reports to SEEDS (check for a t64 variant)" >&2
  ldd "$CHROME_BIN" 2>/dev/null | grep "not found" >&2
  exit 1
}
"$CHROME_BIN" --version
echo "==> ok. source ci/browser/env.sh in any shell that needs a browser."
