/**
 * One place that knows how to start Chrome in this sandbox.
 *
 * Every capture script needs the same three things — the binary, the unpacked
 * library prefix, and the fontconfig path — and getting any of them wrong fails
 * in a way that reads like a page bug rather than an environment bug. So it
 * lives here once.
 *
 * `env.sh` is generated by install-chrome-deps.sh and is deliberately NOT
 * committed: the prefix path differs per host, and a stale committed one would
 * point at a directory that does not exist. We read the environment instead, and
 * fall back to the conventional locations so a plain `node ci/browser/capture.mjs`
 * works without sourcing anything.
 */
import { existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import puppeteer from 'puppeteer-core';

const DEFAULT_PREFIX = '/paperclip/.cache/chrome-deps';

export function findChrome() {
  if (process.env.CHROME_BIN && existsSync(process.env.CHROME_BIN)) return process.env.CHROME_BIN;
  // The puppeteer cache ships a versioned directory; take the newest.
  const cache = process.env.PUPPETEER_CACHE_DIR ?? '/paperclip/.cache/puppeteer';
  try {
    const found = execFileSync('bash', ['-lc',
      `ls -d ${cache}/chrome/linux-*/chrome-linux64/chrome 2>/dev/null | sort -V | tail -1`,
    ], { encoding: 'utf8' }).trim();
    if (found && existsSync(found)) return found;
  } catch { /* fall through to a system Chrome */ }
  for (const c of ['/usr/bin/google-chrome-stable', '/usr/bin/google-chrome', '/usr/bin/chromium']) {
    if (existsSync(c)) return c;
  }
  throw new Error('no Chrome found — run ci/browser/install-chrome-deps.sh, or set CHROME_BIN');
}

/**
 * Assert Chrome can actually start before a caller spends minutes on captures.
 * `--version` is NOT this check: it succeeds on a binary that cannot render,
 * because it never loads the graphics stack. Rendering a DOM does.
 */
export function preflight(chrome = findChrome()) {
  const missing = execFileSync('bash', ['-lc',
    `ldd ${JSON.stringify(chrome)} 2>/dev/null | grep -c 'not found' || true`,
  ], { encoding: 'utf8', env: chromeEnv() }).trim();
  if (Number(missing) > 0) {
    throw new Error(`Chrome is missing ${missing} shared libraries — run ci/browser/install-chrome-deps.sh`);
  }
  return { chrome, missingLibraries: 0 };
}

export function chromeEnv() {
  const prefix = process.env.CHROME_DEPS_PREFIX
    ?? (existsSync(DEFAULT_PREFIX) ? DEFAULT_PREFIX : null);
  if (!prefix) return { ...process.env };
  return {
    ...process.env,
    LD_LIBRARY_PATH: [
      `${prefix}/usr/lib/x86_64-linux-gnu`,
      `${prefix}/lib/x86_64-linux-gnu`,
      process.env.LD_LIBRARY_PATH,
    ].filter(Boolean).join(':'),
    FONTCONFIG_PATH: process.env.FONTCONFIG_PATH ?? `${prefix}/etc/fonts`,
  };
}

export async function launch() {
  const chrome = findChrome();
  preflight(chrome);
  return puppeteer.launch({
    executablePath: chrome,
    headless: true,
    // --hide-scrollbars keeps a shot the width it claims to be. dbus errors in
    // the log are benign: there is no system bus here and Chrome renders anyway.
    args: ['--no-sandbox', '--disable-gpu', '--disable-dev-shm-usage', '--hide-scrollbars'],
    env: chromeEnv(),
  });
}

/**
 * Real device emulation, not a window size.
 *
 * `--window-size=360,x` leaves deviceScaleFactor and isMobile unset, so the shot
 * is a *crop of the desktop layout* — it looks like a broken responsive page and
 * sends you hunting a CSS bug that isn't there. A real 360px phone shot is 720px
 * wide on disk, because deviceScaleFactor is 2. That width is how a reviewer
 * tells a genuine mobile capture from a cropped desktop one.
 */
export const VIEWPORTS = {
  mobile: { name: 'mobile', width: 360, height: 780, deviceScaleFactor: 2, isMobile: true, hasTouch: true },
  desktop: { name: 'desktop', width: 1280, height: 900, deviceScaleFactor: 1, isMobile: false, hasTouch: false },
};

/**
 * Install the layout-shift observer BEFORE navigation.
 *
 * Attach it after `goto` and you measure CLS of 0 for a page that shifts badly —
 * the entries you care about have already been emitted. A confident, wrong zero
 * is worse than no number at all.
 */
export async function observeCls(page) {
  await page.evaluateOnNewDocument(() => {
    window.__cls = 0;
    new PerformanceObserver((list) => {
      for (const entry of list.getEntries()) {
        if (!entry.hadRecentInput) window.__cls += entry.value;
      }
    }).observe({ type: 'layout-shift', buffered: true });
  });
}
